// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAssistantData, DeleteDraftConfigurationData, DiscardDraftChangesData, GetConfigurationHistoryData, GetConfigurationHistoryErrors, GetCurrentStatusliveDraftInfoData, GetCurrentStatusliveDraftInfoErrors, GetDetailedCallLogDataData, GetDetailedCallLogDataErrors, GetDraftConfigurationcreatesOneIfNeededData, GetDraftConfigurationcreatesOneIfNeededErrors, ListAllConfigurationsForAnAssistantWithHistoryData, ListAllConfigurationsForAnAssistantWithHistoryErrors, ListAvailablePhoneNumbersData, ListAvailablePhoneNumbersErrors, ProvisionAndAssignNumberData, PublishDraftConfigurationData, RevertToPreviousConfigurationData, SearchByTextData, SearchByTextErrors, ShowPlaceDetailsData, ShowPlaceDetailsErrors, ShowSpecificAssistantData, ShowSpecificAssistantErrors, ShowSpecificConfigurationData, ShowSpecificConfigurationErrors, UpdateArchiveStatusOfACallLogData, UpdateAssistantnameOnlyData, UpdateDraftConfigurationData, UpdateReadunreadStatusOfACallLogData, UpdateSpecificConfigurationifItsADraftData } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AssistantApi {
    /**
     * Delete assistant
     */
    public static deleteAssistant<ThrowOnError extends boolean = false>(options: Options<DeleteAssistantData, ThrowOnError>) {
        return (options.client ?? client).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{id}',
            ...options
        });
    }
    
    /**
     * Show specific assistant
     */
    public static showSpecificAssistant<ThrowOnError extends boolean = false>(options: Options<ShowSpecificAssistantData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, ShowSpecificAssistantErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{id}',
            ...options
        });
    }
    
    /**
     * Update assistant (name only)
     */
    public static updateAssistantnameOnly<ThrowOnError extends boolean = false>(options: Options<UpdateAssistantnameOnlyData, ThrowOnError>) {
        return (options.client ?? client).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class AssistantConfigurationApi {
    /**
     * Get current status (live + draft info)
     */
    public static getCurrentStatusliveDraftInfo<ThrowOnError extends boolean = false>(options: Options<GetCurrentStatusliveDraftInfoData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, GetCurrentStatusliveDraftInfoErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/status',
            ...options
        });
    }
    
    /**
     * Get configuration history
     */
    public static getConfigurationHistory<ThrowOnError extends boolean = false>(options: Options<GetConfigurationHistoryData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, GetConfigurationHistoryErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/history',
            ...options
        });
    }
    
    /**
     * List all configurations for an assistant with history
     */
    public static listAllConfigurationsForAnAssistantWithHistory<ThrowOnError extends boolean = false>(options: Options<ListAllConfigurationsForAnAssistantWithHistoryData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, ListAllConfigurationsForAnAssistantWithHistoryErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/configurations',
            ...options
        });
    }
    
    /**
     * Delete draft configuration
     */
    public static deleteDraftConfiguration<ThrowOnError extends boolean = false>(options: Options<DeleteDraftConfigurationData, ThrowOnError>) {
        return (options.client ?? client).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/configurations/{id}',
            ...options
        });
    }
    
    /**
     * Show specific configuration
     */
    public static showSpecificConfiguration<ThrowOnError extends boolean = false>(options: Options<ShowSpecificConfigurationData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, ShowSpecificConfigurationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/configurations/{id}',
            ...options
        });
    }
    
    /**
     * Update specific configuration (if it's a draft)
     */
    public static updateSpecificConfigurationifItsADraft<ThrowOnError extends boolean = false>(options: Options<UpdateSpecificConfigurationifItsADraftData, ThrowOnError>) {
        return (options.client ?? client).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/configurations/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class AssistantLifecycleApi {
    /**
     * Discard draft changes
     */
    public static discardDraftChanges<ThrowOnError extends boolean = false>(options: Options<DiscardDraftChangesData, ThrowOnError>) {
        return (options.client ?? client).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/draft',
            ...options
        });
    }
    
    /**
     * Get draft configuration (creates one if needed)
     */
    public static getDraftConfigurationcreatesOneIfNeeded<ThrowOnError extends boolean = false>(options: Options<GetDraftConfigurationcreatesOneIfNeededData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, GetDraftConfigurationcreatesOneIfNeededErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/draft',
            ...options
        });
    }
    
    /**
     * Update draft configuration
     */
    public static updateDraftConfiguration<ThrowOnError extends boolean = false>(options: Options<UpdateDraftConfigurationData, ThrowOnError>) {
        return (options.client ?? client).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/draft',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Publish draft configuration
     */
    public static publishDraftConfiguration<ThrowOnError extends boolean = false>(options: Options<PublishDraftConfigurationData, ThrowOnError>) {
        return (options.client ?? client).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/publish',
            ...options
        });
    }
    
    /**
     * Revert to previous configuration
     */
    public static revertToPreviousConfiguration<ThrowOnError extends boolean = false>(options: Options<RevertToPreviousConfigurationData, ThrowOnError>) {
        return (options.client ?? client).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/assistants/{assistant_id}/revert',
            ...options
        });
    }
}

export class CallLogs {
    /**
     * Get detailed call log data
     *
     * Returns all available call log information
     */
    public static getDetailedCallLogData<ThrowOnError extends boolean = false>(options: Options<GetDetailedCallLogDataData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, GetDetailedCallLogDataErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/call-logs/{callLog_id}',
            ...options
        });
    }
    
    /**
     * Update read/unread status of a call log
     */
    public static updateReadunreadStatusOfACallLog<ThrowOnError extends boolean = false>(options: Options<UpdateReadunreadStatusOfACallLogData, ThrowOnError>) {
        return (options.client ?? client).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/call-logs/{callLog_id}/read-status',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update archive status of a call log
     *
     * Note: Archive functionality is not yet implemented in the database schema.
     * This endpoint returns a 501 Not Implemented response.
     */
    public static updateArchiveStatusOfACallLog<ThrowOnError extends boolean = false>(options: Options<UpdateArchiveStatusOfACallLogData, ThrowOnError>) {
        return (options.client ?? client).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/call-logs/{callLog_id}/archive-status',
            ...options
        });
    }
}

export class GooglePlaces {
    /**
     * Search by text
     */
    public static searchByText<ThrowOnError extends boolean = false>(options: Options<SearchByTextData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, SearchByTextErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/places/search',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Show place details
     */
    public static showPlaceDetails<ThrowOnError extends boolean = false>(options: Options<ShowPlaceDetailsData, ThrowOnError>) {
        return (options.client ?? client).get<unknown, ShowPlaceDetailsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/places/{id}',
            ...options
        });
    }
}

export class TwilioNumbers {
    /**
     * List available phone numbers
     *
     * Search and retrieve available Twilio phone numbers that can be provisioned for the onboarding tenant
     */
    public static listAvailablePhoneNumbers<ThrowOnError extends boolean = false>(options?: Options<ListAvailablePhoneNumbersData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, ListAvailablePhoneNumbersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/onboarding/twilio-numbers',
            ...options
        });
    }
    
    /**
     * Provision and assign number
     *
     * Provision a Twilio phone number from the default account and assign it to the onboarding tenant
     */
    public static provisionAndAssignNumber<ThrowOnError extends boolean = false>(options: Options<ProvisionAndAssignNumberData, ThrowOnError>) {
        return (options.client ?? client).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/onboarding/twilio-numbers',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
