// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://reception.callkaira.test' | (string & {});
};

export type DeleteAssistantData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{id}';
};

export type ShowSpecificAssistantData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{id}';
};

export type ShowSpecificAssistantErrors = {
    401: {
        message?: string;
    };
};

export type ShowSpecificAssistantError = ShowSpecificAssistantErrors[keyof ShowSpecificAssistantErrors];

export type UpdateAssistantnameOnlyData = {
    body: {
        /**
         * Must not be greater than 255 characters.
         */
        name: string;
        is_active?: boolean;
    };
    path: {
        /**
         * The ID of the assistant.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{id}';
};

export type GetCurrentStatusliveDraftInfoData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/status';
};

export type GetCurrentStatusliveDraftInfoErrors = {
    401: {
        message?: string;
    };
};

export type GetCurrentStatusliveDraftInfoError = GetCurrentStatusliveDraftInfoErrors[keyof GetCurrentStatusliveDraftInfoErrors];

export type GetConfigurationHistoryData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/history';
};

export type GetConfigurationHistoryErrors = {
    401: {
        message?: string;
    };
};

export type GetConfigurationHistoryError = GetConfigurationHistoryErrors[keyof GetConfigurationHistoryErrors];

export type ListAllConfigurationsForAnAssistantWithHistoryData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/configurations';
};

export type ListAllConfigurationsForAnAssistantWithHistoryErrors = {
    401: {
        message?: string;
    };
};

export type ListAllConfigurationsForAnAssistantWithHistoryError = ListAllConfigurationsForAnAssistantWithHistoryErrors[keyof ListAllConfigurationsForAnAssistantWithHistoryErrors];

export type DeleteDraftConfigurationData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
        /**
         * The ID of the configuration.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/configurations/{id}';
};

export type ShowSpecificConfigurationData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
        /**
         * The ID of the configuration.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/configurations/{id}';
};

export type ShowSpecificConfigurationErrors = {
    401: {
        message?: string;
    };
};

export type ShowSpecificConfigurationError = ShowSpecificConfigurationErrors[keyof ShowSpecificConfigurationErrors];

export type UpdateSpecificConfigurationifItsADraftData = {
    body?: {
        is_active?: boolean;
        passthrough_number?: string | null;
        answering_mode?: 'all_calls' | 'unanswered_calls';
        ai_provider?: 'gemini' | 'openai';
        ai_model_config?: {
            [key: string]: unknown;
        };
        call_handling_config?: {
            [key: string]: unknown;
        };
        /**
         * The <code>id</code> of an existing record in the business_profiles table.
         */
        business_profile_id?: string;
    };
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
        /**
         * The ID of the configuration.
         */
        id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/configurations/{id}';
};

export type DiscardDraftChangesData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/draft';
};

export type GetDraftConfigurationcreatesOneIfNeededData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/draft';
};

export type GetDraftConfigurationcreatesOneIfNeededErrors = {
    401: {
        message?: string;
    };
};

export type GetDraftConfigurationcreatesOneIfNeededError = GetDraftConfigurationcreatesOneIfNeededErrors[keyof GetDraftConfigurationcreatesOneIfNeededErrors];

export type UpdateDraftConfigurationData = {
    body?: {
        is_active?: boolean;
        passthrough_number?: string | null;
        answering_mode?: 'all_calls' | 'unanswered_calls';
        ai_provider?: 'gemini' | 'openai';
        ai_model_config?: {
            [key: string]: unknown;
        };
        call_handling_config?: {
            [key: string]: unknown;
        };
        /**
         * The <code>id</code> of an existing record in the business_profiles table.
         */
        business_profile_id?: string;
    };
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/draft';
};

export type PublishDraftConfigurationData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/publish';
};

export type RevertToPreviousConfigurationData = {
    body?: never;
    path: {
        /**
         * The ID of the assistant.
         */
        assistant_id: number;
    };
    query?: never;
    url: '/api/assistants/{assistant_id}/revert';
};

export type GetDetailedCallLogDataData = {
    body?: never;
    path: {
        /**
         * The ID of the callLog.
         */
        callLog_id: number;
    };
    query?: never;
    url: '/api/call-logs/{callLog_id}';
};

export type GetDetailedCallLogDataErrors = {
    401: {
        message?: string;
    };
};

export type GetDetailedCallLogDataError = GetDetailedCallLogDataErrors[keyof GetDetailedCallLogDataErrors];

export type UpdateReadunreadStatusOfACallLogData = {
    body: {
        read_status: string;
    };
    path: {
        /**
         * The ID of the callLog.
         */
        callLog_id: number;
    };
    query?: never;
    url: '/api/call-logs/{callLog_id}/read-status';
};

export type UpdateArchiveStatusOfACallLogData = {
    body?: never;
    path: {
        /**
         * The ID of the callLog.
         */
        callLog_id: number;
    };
    query?: never;
    url: '/api/call-logs/{callLog_id}/archive-status';
};

export type SearchByTextData = {
    body: {
        query: string;
        /**
         * Must be 2 characters.
         */
        countryCode: string;
        /**
         * Must be at least 1. Must not be greater than 20.
         */
        pageSize?: number;
        /**
         * Must be at least 0.
         */
        pageNumber?: number;
    };
    path?: never;
    query?: never;
    url: '/api/places/search';
};

export type SearchByTextErrors = {
    500: {
        error?: string;
    };
};

export type SearchByTextError = SearchByTextErrors[keyof SearchByTextErrors];

export type ShowPlaceDetailsData = {
    body?: never;
    path: {
        /**
         * The ID of the place.
         */
        id: string;
    };
    query?: never;
    url: '/api/places/{id}';
};

export type ShowPlaceDetailsErrors = {
    500: {
        error?: string;
    };
};

export type ShowPlaceDetailsError = ShowPlaceDetailsErrors[keyof ShowPlaceDetailsErrors];

export type ListAvailablePhoneNumbersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/onboarding/twilio-numbers';
};

export type ListAvailablePhoneNumbersErrors = {
    500: {
        message?: string;
    };
};

export type ListAvailablePhoneNumbersError = ListAvailablePhoneNumbersErrors[keyof ListAvailablePhoneNumbersErrors];

export type ProvisionAndAssignNumberData = {
    body: {
        /**
         * The Twilio SID of the phone number to provision and assign to the tenant.
         */
        number_sid: string;
    };
    path?: never;
    query?: never;
    url: '/api/onboarding/twilio-numbers';
};
